### ISSUE TITLE
Download doesn't start

### ISSUE THREAD

**Issue by praeludiumOrbis** [HoloArchivists/OPENREC-dl#3]
```
py openrec-dl.py https://www.openrec.tv/live/u7ERt3xbl4i
Traceback (most recent call last):
  File "E:\openrec-dl.py", line 437, in <module>
    main()
  File "E:\openrec-dl.py", line 425, in main
    dl_movie(api_session, openrec_m.group("id"))
  File "E:\openrec-dl.py", line 216, in dl_movie
    formats_list = get_m3u8_info(m_json["media"]["url"])
  File "E:\openrec-dl.py", line 312, in get_m3u8_info
    m3u8_text = requests.get(playlist_link).text
  File "C:\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Python39\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Python39\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'playlist.m3u8': No schema supplied. Perhaps you meant http://playlist.m3u8?
```

**Comment by CetaceanNation** [comment]
The API is not returning the normally available public playlist URL. I can't say I know enough about the platform to know why this video would not return it while others do. Additionally, the [playlist I have been hardcoding as `playlist.m3u8`](https://github.com/CetaceanNation/OPENREC-dl/blob/abc76cc8ceec0174939a155410b1b439731074df/openrec-dl.py#L210) is instead `normal.m3u8` for this video. May need to add a test for which is valid if there is no indicator for this case.
