### ISSUE TITLE
PermissionError at the very end of a download

### ISSUE THREAD

**Issue by praeludiumOrbis** [HoloArchivists/OPENREC-dl#5]
```
E:\>openrec-dl.py --cookies openrec.txt --write-info-json --write-thumbnail --write-live-chat https://www.openrec.tv/live/u7ERt3xbl4i
[info:u7ERt3xbl4i] no public playlist found
[info:u7ERt3xbl4i] writing video information to 'osu owo_ [u7ERt3xbl4i].info.json'
[thumbnail:u7ERt3xbl4i] writing thumbnail to 'osu owo_ [u7ERt3xbl4i].png'
[live-chat:u7ERt3xbl4i] writing live chat to osu owo_ [u7ERt3xbl4i].live_chat.json
[movie:u7ERt3xbl4i] writing video to 'osu owo_ [u7ERt3xbl4i].ts'
←[K[movie:u7ERt3xbl4i] |████████████████████████████████| 100.0% ETA 0:0076
←[?25hTraceback (most recent call last):
  File "E:\openrec-dl.py", line 515, in <module>
    main()
  File "E:\openrec-dl.py", line 503, in main
    dl_movie(pub_api_session, priv_api_session, openrec_m.group("id"))
  File "E:\openrec-dl.py", line 293, in dl_movie
    dl_m3u8_video(movie_id, movie_string, downloading_format)
  File "E:\openrec-dl.py", line 327, in dl_m3u8_video
    os.rename(f"{movie_path}.ts.tmp", f"{movie_path}.ts")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\osu owo_ [u7ERt3xbl4i].ts.tmp' -> 'E:\\osu owo_ [u7ERt3xbl4i].ts'
```
Not sure what causes this, potentially this is an issue on my side? Will try another download, maybe with admin perms even though that's likely not related to it.

**Comment by praeludiumOrbis** [comment]
Edit: Same thing in new folder with admin perms
```
E:\Openrec Downloader>openrec-dl.py --cookies openrec.txt --write-info-json --write-thumbnail --write-live-chat https://www.openrec.tv/live/3ODrqB5XsMf
[openrec-dl] could not find cookies file 'openrec.txt', continuing without cookies
[info:3ODrqB5XsMf] writing video information to 'some osu [3ODrqB5XsMf].info.json'
[thumbnail:3ODrqB5XsMf] writing thumbnail to 'some osu [3ODrqB5XsMf].png'
[live-chat:3ODrqB5XsMf] writing live chat to some osu [3ODrqB5XsMf].live_chat.json
[movie:3ODrqB5XsMf] writing video to 'some osu [3ODrqB5XsMf].ts'
←[K[movie:3ODrqB5XsMf] |████████████████████████████████| 100.0% ETA 0:00
←[?25hTraceback (most recent call last):
  File "E:\Openrec Downloader\openrec-dl.py", line 515, in <module>
    main()
  File "E:\Openrec Downloader\openrec-dl.py", line 503, in main
    dl_movie(pub_api_session, priv_api_session, openrec_m.group("id"))
  File "E:\Openrec Downloader\openrec-dl.py", line 293, in dl_movie
    dl_m3u8_video(movie_id, movie_string, downloading_format)
  File "E:\Openrec Downloader\openrec-dl.py", line 327, in dl_m3u8_video
    os.rename(f"{movie_path}.ts.tmp", f"{movie_path}.ts")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\Openrec Downloader\\some osu [3ODrqB5XsMf].ts.tmp' -> 'E:\\Openrec Downloader\\some osu [3ODrqB5XsMf].ts'
```

**Comment by CetaceanNation** [comment]
Oddly didn't run into this before, but the fix seems to be that I just wasn't closing the file handle once the download finished. Sometimes this isn't an issue for unknown reasons.

**Comment by praeludiumOrbis** [comment]
Looks like the pull request fixed this: 
```
E:\openrecdl>openrec-dl.py --cookies openrec.txt --write-info-json --write-live-chat --write-thumbnail https://www.openrec.tv/live/3ODrqB5XsMf
[info:3ODrqB5XsMf] writing video information to 'some osu [3ODrqB5XsMf].info.json'
[thumbnail:3ODrqB5XsMf] writing thumbnail to 'some osu [3ODrqB5XsMf].png'
[live-chat:3ODrqB5XsMf] writing live chat to some osu [3ODrqB5XsMf].live_chat.json
[movie:3ODrqB5XsMf] writing video to 'some osu [3ODrqB5XsMf].ts'
←[K[movie:3ODrqB5XsMf] |████████████████████████████████| 100.0% ETA 0:00
[mpeg-convert] converting video to 'some osu [3ODrqB5XsMf].mp4'
←[?25h
```
Gotta test once more and report back!

**Comment by praeludiumOrbis** [comment]
Yep, it works fine now, even though I'm not sure what the text at the end is supposed to mean.
```
E:\openrecdl>openrec-dl.py --cookies openrec.txt --write-info-json --write-live-chat --write-thumbnail https://www.openrec.tv/live/8l5B8399tV9
[info:8l5B8399tV9] writing video information to '1 tourney match  [8l5B8399tV9].info.json'
[thumbnail:8l5B8399tV9] writing thumbnail to '1 tourney match  [8l5B8399tV9].png'
[live-chat:8l5B8399tV9] writing live chat to 1 tourney match  [8l5B8399tV9].live_chat.json
[movie:8l5B8399tV9] writing video to '1 tourney match  [8l5B8399tV9].ts'
←[K[movie:8l5B8399tV9] |████████████████████████████████| 100.0% ETA 0:00
[mpeg-convert] converting video to '1 tourney match  [8l5B8399tV9].mp4'
←[?25h
```
